language: php
sudo: false
git:
  depth: 5
  submodules: false
addons:
  apt:
    packages:
      - openjdk-8-jre-headless
matrix:
  include:
    - php: 7.3
      env: ES=5
  include:
    - php: 7.3
      env: ES=6

before_install:
  - export NEOS_TARGET_VERSION=5.1
  - cd ..
  - if [ "$ES" = 5 ]; then wget --no-check-certificate https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.15.zip && unzip elasticsearch-5.6.15.zip && mv elasticsearch-5.6.15 elasticsearch; fi
  - if [ "$ES" = 6 ]; then wget --no-check-certificate https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.6.tar.gz && tar xvfz elasticsearch-6.8.6.tar.gz && mv elasticsearch-6.8.6 elasticsearch; fi
  - cd elasticsearch
  - bin/elasticsearch -d
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git -b ${NEOS_TARGET_VERSION}
  - cd neos-base-distribution
  - composer require --no-update --no-interaction neos/content-repository-search:dev-master
  - composer require --no-update --no-interaction flowpack/elasticsearch-contentrepositoryadaptor:dev-master
  - composer require --no-update --no-interaction neos/nodetypes
  - composer remove --no-update --no-interaction neos/site-kickstarter
install:
  - composer install --no-interaction
  - cd ..
  - rm -rf neos-base-distribution/Packages/Application/Flowpack.ElasticSearch.ContentRepositoryAdaptor
  - mv Flowpack.ElasticSearch.ContentRepositoryAdaptor neos-base-distribution/Packages/Application/Flowpack.ElasticSearch.ContentRepositoryAdaptor
  - cd neos-base-distribution
script:
  - bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Flowpack.ElasticSearch.ContentRepositoryAdaptor/Tests/Unit
  - if [ "$ES" = 5 ]; then FLOW_CONTEXT="Testing/ElasticVersion5" bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Flowpack.ElasticSearch.ContentRepositoryAdaptor/Tests/Functional; fi
  - if [ "$ES" = 6 ]; then FLOW_CONTEXT="Testing/ElasticVersion6" bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Flowpack.ElasticSearch.ContentRepositoryAdaptor/Tests/Functional; fi
