Neos:
  ContentRepository:
    Search:
      elasticSearch:
        indexName: neoscr_testing
        log:
          backendOptions:
            fileBackend:
              logFileURL: '%FLOW_PATH_DATA%Logs/ElasticSearch_Testing.log'
              severityThreshold: '%LOG_DEBUG%'
      realtimeIndexing:
        enabled: false

Flowpack:
  ElasticSearch:
    ContentRepositoryAdaptor:
      command:
        useSubProcesses: false
