Flowpack:
  ElasticSearch:
    ContentRepositoryAdaptor:

      indexName: typo3cr

      log:
        backendOptions:
          logFileURL: %FLOW_PATH_DATA%Logs/Indexer.log
          createParentDirectories: TRUE
          severityThreshold: %LOG_INFO%
          maximumLogFileSize: 10485760
          logFilesToKeep: 1
          logMessageOrigin: FALSE

      defaultConfigurationPerType:

        string:
          mapping:
            type: string

        boolean:
          mapping:
            type: boolean

        integer:
          mapping:
            type: integer

        date:
          mapping:
            type: date

        'TYPO3\Media\Domain\Model\Video':
          mapping: '' # deliberately don't map this

        'TYPO3\Media\Domain\Model\ImageVariant':
          mapping: '' # deliberately don't map this