Flowpack:
  ElasticSearch:
    ContentRepositoryAdaptor:
      command:
        useSubProcesses: true
      indexing:
        batchSize:
          elements: 500
          octets: 40000000
      configuration:
        nodeTypes:
          '*':
            indexed: true
      driver:
        version: '6.x'
        mapping:
          6.x:
            query:
              className: Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version6\Query\FilteredQuery
              arguments:
                request:
                  query:
                    bool:
                      must:
                        - match_all:
                            boost: 1.0 # force match_all to be an object
                      filter:
                        bool:
                          must: []
                          should: []
                          must_not:
                            - term:
                                _hidden: true
                            - range:
                                _hiddenBeforeDateTime:
                                  gt: now
                            - range:
                                _hiddenAfterDateTime:
                                  lt: now
                  _source:
                    - '__path'

                unsupportedFieldsInCountRequest:
                  - '_source'
                  - 'sort'
                  - 'from'
                  - 'size'
                  - 'highlight'
                  - 'aggs'
                  - 'aggregations'
                  - 'suggest'

                # Parameters for the query string query used by the fullText() operation
                # See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-multi-field
                # for all available parameters
                queryStringParameters:
                  default_operator: or
                  fields:
                    - __fulltext.h1^20
                    - __fulltext.h2^12
                    - __fulltext.h3^10
                    - __fulltext.h4^5
                    - __fulltext.h5^3
                    - __fulltext.h6^2
                    - __fulltext.text^1

            document:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version6\DocumentDriver'
            indexer:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version6\IndexerDriver'
            indexManagement:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version6\IndexDriver'
            request:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version6\RequestDriver'
            system:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version6\SystemDriver'
            nodeTypeMappingBuilder:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version6\Mapping\NodeTypeMappingBuilder'
