Flowpack:
  ElasticSearch:
    ContentRepositoryAdaptor:

      indexName: typo3cr

      log:
        backendOptions:
          fileBackend:
            logFileURL: %FLOW_PATH_DATA%Logs/ElasticSearch.log
            createParentDirectories: TRUE
            severityThreshold: %LOG_DEBUG%
            maximumLogFileSize: 10485760
            logFilesToKeep: 1
            logMessageOrigin: FALSE

          ansiConsoleBackend:
            disableAnsi: false

      defaultConfigurationPerType:

        string:
          mapping:
            type: string
          indexing: ${value}

        boolean:
          mapping:
            type: boolean
          indexing: ${value}

        integer:
          mapping:
            type: integer
          indexing: ${value}

        date:
          mapping:
            type: date
          indexing: ${value.format('c')}

        'TYPO3\Media\Domain\Model\Video':
          mapping: '' # deliberately don't map or index this
          indexing: ''

        'TYPO3\Media\Domain\Model\ImageVariant':
          mapping: '' # deliberately don't map or index this
          indexing: ''

        'references':
          mapping:
            type: string # an array of strings, to be precise
            index: not_analyzed
          indexing: ${ElasticSearch.convertArrayOfNodesToArrayOfNodeIdentifiers(value)}

        'reference':
          mapping:
            type: string
            index: not_analyzed
          indexing: ${value.getIdentifier()}


      # Default context objects that are available in Eel expressions
      #
      # New variables should be added with a package key prefix. Example:
      #
      #   defaultContext:
      #     'MyPackage.String': 'MyPackage\Helper\StringHelper'
      #
      defaultContext:
        String: 'TYPO3\Eel\Helper\StringHelper'
        Array: 'TYPO3\Eel\Helper\ArrayHelper'
        Date: 'TYPO3\Eel\Helper\DateHelper'
        ElasticSearch: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Eel\ElasticSearchHelper'


TYPO3:
  TypoScript:
    # TODO: refactor DefaultContext to Eel
    defaultContext:
      ElasticSearch: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Eel\ElasticSearchHelper'