Flowpack:
  ElasticSearch:
    ContentRepositoryAdaptor:
      command:
        useSubProcesses: true
      indexing:
        batchSize:
          elements: 50
          octets: 40000000
      driver:
        version: '5.x'
        mapping:
          5.x:
            query:
              className: Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version5\Query\FilteredQuery
              arguments:
                request:
                  query:
                    bool:
                      must:
                        - match_all:
                            boost: 1.0 # force match_all to be an object
                      filter:
                        bool:
                          must: []
                          should: []
                          must_not:
                            - term:
                                _hidden: true
                            - range:
                                _hiddenBeforeDateTime:
                                  gt: now
                            - range:
                                _hiddenAfterDateTime:
                                  lt: now
                  _source:
                    - '__path'
                unsupportedFieldsInCountRequest:
                  - '_source'
                  - 'sort'
                  - 'from'
                  - 'size'
                  - 'highlight'
                  - 'aggs'
                  - 'aggregations'
                  - 'suggest'
            document:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version5\DocumentDriver'
            indexer:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version5\IndexerDriver'
            indexManagement:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version5\IndexDriver'
            request:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version5\RequestDriver'
            system:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version5\SystemDriver'
            nodeTypeMappingBuilder:
              className: 'Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\Version5\Mapping\NodeTypeMappingBuilder'
